apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: cloud-native-demo
  name: cloud-native-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cloud-native-demo
  template:
    metadata:
      labels:
        run: cloud-native-demo
    spec:
      containers:
      - image: cloud-native-demo:1
        imagePullPolicy: IfNotPresent
        name: cloud-native-demo
        env:
        - name: USER_DEFINED_1
          value: Custom value 1
        - name: USER_DEFINED_2
          value: Custom value 2
        resources:
          limits:
            cpu: 1
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 2
